name: Generate DocC
on:
  workflow_dispatch:

env:
  GH-PAGES-BRANCH: 'gh-pages'
  GH-PAGES-PATH: 'gh-pages'

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Git checkout main
        uses: actions/checkout@v3

      - name: Git checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GH-PAGES-BRANCH }}
          path: ${{ env.GH-PAGES-PATH }}

      - name: Build DocC for Lytics
        uses: ./.github/actions/generate-docc
        with:
          hosting-base-path: ios-sdk
          output-path: ${{ env.GH-PAGES-PATH }}
          target: Lytics

      - name: Build DocC for LyticsUI
        uses: ./.github/actions/generate-docc
        with:
          hosting-base-path: ios-sdk
          output-path: ${{ env.GH-PAGES-PATH }}
          target: LyticsUI

      - name: Commit
        id: commit
        run: |
            CURRENT_COMMIT_HASH=`git rev-parse --short HEAD`
            cd ${{ env.GH-PAGES-PATH }}
            git add docs
            if [ -n "$(git status --porcelain)" ]; then
                echo "Documentation changes found. Commiting the changes to the pages branch and pushing to origin."
                git commit -m "Update GitHub Pages documentation site to '$CURRENT_COMMIT_HASH'."
                git push origin HEAD:${{ env.GH-PAGES-BRANCH }}
            else
              # No changes found, nothing to commit.
              echo "No documentation changes found."
            fi
