name: Tag Release
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.head_ref == 'release'
    outputs:
      current-version: ${{ steps.get-version.outputs.current-version }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Get version
        id: get-version
        shell: bash
        run: |
          VERSION=$(grep -Eo '([0-9]+\.*)+' ${{ vars.VERSION_FILE_PATH }})
          echo "current-version=$VERSION" >> $GITHUB_ENV
          echo "current-version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ vars.FRONTEND_PROJECT_BOT_APP_ID }}
          private_key: ${{ secrets.FRONTEND_PROJECT_BOT_TOKEN }}

      - name: Push tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.current-version }}',
              sha: '${{ github.sha }}'
            })

  cocoapods:
    runs-on: macOS-latest
    needs: tag
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Publish podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          LIB_VERSION: ${{ needs.tag.outputs.current-version }}
        run: |
          pod trunk push ${{ vars.SDK_PODSPEC_PATH }} --allow-warnings
          pod trunk push ${{ vars.UI_PODSPEC_PATH }} --allow-warnings
