name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  unit_tests:
    name: Run Tests
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and test
        uses: mxcl/xcodebuild@v1
        with:
          xcode: ^14
          platform: iOS
          code-coverage: true
      - name: Convert coverage
        uses: sersoft-gmbh/swift-coverage-action@v3
        id: coverage-files
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}
