name: Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  unit_tests:
    name: Run Tests
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test
        uses: mxcl/xcodebuild@v2
        with:
          xcode: ^14
          platform: iOS
          code-coverage: true

      - name: Convert coverage
        uses: sersoft-gmbh/swift-coverage-action@v4
        id: coverage-files

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}
